"""`heartbeat_events` table — TimescaleDB hypertable.

The model is here for ORM convenience. TimescaleDB-specific DDL (hypertable,
compression, retention) lives EXCLUSIVELY in raw-SQL blocks of the Alembic
migration, never in autogenerated diffs. See `alembic/versions/0001_initial.py`.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any

from sqlalchemy import BigInteger, ForeignKey, PrimaryKeyConstraint, Text
from sqlalchemy.orm import Mapped, mapped_column

from aglaea.models._portable import PortableJSONB
from aglaea.models.base import Base


class HeartbeatEvent(Base):
    __tablename__ = "heartbeat_events"

    ts: Mapped[datetime] = mapped_column(nullable=False)
    service_id: Mapped[int] = mapped_column(
        BigInteger,
        ForeignKey("services.id", ondelete="CASCADE"),
        nullable=False,
    )
    status: Mapped[str] = mapped_column(Text, nullable=False)
    subchecks: Mapped[dict[str, Any] | None] = mapped_column(PortableJSONB, nullable=True)
    metrics: Mapped[dict[str, Any] | None] = mapped_column(PortableJSONB, nullable=True)
    message: Mapped[str | None] = mapped_column(Text, nullable=True)
    source: Mapped[str] = mapped_column(Text, nullable=False)
    client_ts: Mapped[datetime | None] = mapped_column(nullable=True)

    __table_args__ = (PrimaryKeyConstraint("service_id", "ts", name="pk_heartbeat_events"),)
