#!/usr/bin/env bash
# Aglaea v0.1 — Bootstrap script (AC3.5, AC3.8)
# Generates secrets, prompts for OAuth credentials, writes .env with chmod 600.
#
# Usage: bash scripts/bootstrap.sh
# Run from the repo root (where .env.example lives).
#
# SECURITY:
#   - Secrets are generated with openssl rand — never dictionary words (AC5.1).
#   - Secret values are written to .env but NEVER echoed to the terminal.
#   - .env is created with chmod 600 (AC5.2).
#   - read -s is used for all interactive secret prompts.
#   - .env is gitignored — never committed.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${REPO_ROOT}/.env"

echo "=== Aglaea v0.1 Bootstrap ==="
echo ""

# Refuse to overwrite an existing .env unless user confirms
if [[ -f "${ENV_FILE}" ]]; then
    echo "WARNING: ${ENV_FILE} already exists."
    read -r -p "Overwrite? [y/N] " _confirm
    if [[ "${_confirm}" != "y" && "${_confirm}" != "Y" ]]; then
        echo "Aborted."
        exit 0
    fi
fi

echo "Generating secrets with openssl rand..."

# Generate secrets — variables hold values in memory only, never printed
POSTGRES_PASSWORD="$(openssl rand -base64 32)"
SESSION_SECRET="$(openssl rand -hex 32)"
OTEL_SHARED_TOKEN="$(openssl rand -hex 32)"

echo "  POSTGRES_PASSWORD  — generated (32 bytes base64)"
echo "  SESSION_SECRET     — generated (32 bytes hex)"
echo "  OTEL_SHARED_TOKEN  — generated (32 bytes hex)"
echo ""

# Prompt for DEEPSEEK_API_KEY (copy from Cerydra's .env — do NOT cat/display it)
echo "DeepSeek API key (copy from ~/Cerydra/.env — value will NOT be shown):"
read -r -s DEEPSEEK_API_KEY
echo "  DEEPSEEK_API_KEY   — set (value hidden)"
echo ""

# Prompt for GitHub OAuth credentials
echo "GitHub OAuth App:"
echo "  Create at: https://github.com/settings/applications/new"
echo "  Homepage URL:       https://status.lushuyu.site"
echo "  Callback URL:       https://status.lushuyu.site/api/auth/github/callback"
echo ""
echo "  Client ID (visible, not secret):"
read -r GITHUB_OAUTH_CLIENT_ID
echo "  Client Secret (value will NOT be shown):"
read -r -s GITHUB_OAUTH_CLIENT_SECRET
echo "  GITHUB_OAUTH_CLIENT_ID     — set"
echo "  GITHUB_OAUTH_CLIENT_SECRET — set (value hidden)"
echo ""

# Prompt for HEALTHCHECKS_SELFPING_URL (optional)
echo "Healthchecks.io self-ping URL (leave empty to disable self-ping worker):"
read -r HEALTHCHECKS_SELFPING_URL
if [[ -z "${HEALTHCHECKS_SELFPING_URL}" ]]; then
    echo "  HEALTHCHECKS_SELFPING_URL  — disabled (empty)"
else
    echo "  HEALTHCHECKS_SELFPING_URL  — set"
fi
echo ""

# Write .env — values are written directly, never echoed via echo to terminal
cat > "${ENV_FILE}" <<EOF
# Aglaea v0.1 — generated by scripts/bootstrap.sh
# chmod 600 enforced — do NOT commit this file.

POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
GITHUB_OAUTH_CLIENT_ID=${GITHUB_OAUTH_CLIENT_ID}
GITHUB_OAUTH_CLIENT_SECRET=${GITHUB_OAUTH_CLIENT_SECRET}
SESSION_SECRET=${SESSION_SECRET}
OTEL_SHARED_TOKEN=${OTEL_SHARED_TOKEN}
BOOTSTRAP_GITHUB_LOGIN=lushuyu
HEALTHCHECKS_SELFPING_URL=${HEALTHCHECKS_SELFPING_URL}
EOF

# Enforce strict permissions — AC5.2
chmod 600 "${ENV_FILE}"

echo "=== .env written to ${ENV_FILE} (chmod 600) ==="
echo ""
echo "=== Next steps ==="
echo ""
echo "1. Update infra/nginx.conf.example:"
echo "   - Replace /etc/ssl/cloudflare/lushuyu.site.{pem,key} with actual CF Origin CA paths."
echo "   - Replace REPLACE_WITH_OTEL_SHARED_TOKEN with the OTEL_SHARED_TOKEN value from .env."
echo "   - Copy to /etc/nginx/sites-available/aglaea.conf and symlink to sites-enabled/."
echo ""
echo "2. Start services:"
echo "   docker compose up -d"
echo ""
echo "3. Run database migrations:"
echo "   docker compose exec aglaea-backend alembic upgrade head"
echo ""
echo "4. Reload nginx:"
echo "   nginx -t && systemctl reload nginx"
echo ""
echo "5. First login:"
echo "   Visit https://status.lushuyu.site/admin and sign in with GitHub."
echo "   The account 'lushuyu' will be auto-inserted into admin_users."
echo ""
echo "6. Register services and generate API tokens via the admin UI."
echo ""
echo "7. Configure OTEL on your devices — see docs/deployment.md for device recipes."
echo ""
echo "REMINDER: The OTEL_SHARED_TOKEN value must also be pasted into nginx.conf."
echo "          Run: grep OTEL_SHARED_TOKEN ${ENV_FILE}"
echo "          (You can read .env on the server directly since it is chmod 600.)"
